{% set name = "seekmer" %}
{% set version = "2019.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../

build:
  number: 3
  script: "python -m pip install . --no-deps -vv"

requirements:
  build:
    - toolchain_c_linux-64
  host:
    - python
    - cython
    - numpy
    - pip
    - pytest-runner
  run:
    - python >=3.5
    - logbook
    - numpy
    - pandas
    - pytables
    - scipy

test:
  requires:
    - pytest
    - pytest-datadir
  commands:
    - pytest --verbose --pyargs {{ name }}

about:
  home: http://github.com/guanlab/{{ name }}
  license: GPL-3.0+
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'A fast RNA-seq analysis tool'
  description: |
    Seekmer is a fast RNA-seq analysis tool written for Python 3.5+.
  dev_url: https://github.com/guanlab/{{ name }}
