stages:
  - test
  - build

test:
  image: condaforge/linux-anvil
  stage: test
  script:
    - conda config --add channels bioconda
    - conda env create -p env/ -f environment.yml
    - source activate env/
    - conda install pytest-cov
    - python3 setup.py build_ext -D CYTHON_TRACE_NOGIL
    - python3 setup.py develop
    - pytest --verbose --cov seekmer/ --pyargs seekmer
  coverage: '/TOTAL.*\s+(\d+%)$/'

build_conda_python35:
  image: condaforge/linux-anvil
  stage: build
  script:
    - conda config --add channels conda-forge/label/cf201901
    - conda config --add channels bioconda
    - conda install -y conda-verify
    - conda config --set anaconda_upload yes
    - >
      conda build --user guanlab --token $ANACONDA_TOKEN
      --python=3.5 recipe/meta.yaml
  except:
    - tags

build_conda_python36:
  image: condaforge/linux-anvil
  stage: build
  script:
    - conda config --add channels conda-forge/label/cf201901
    - conda config --add channels bioconda
    - conda install -y conda-verify
    - conda config --set anaconda_upload yes
    - >
      conda build --user guanlab --token $ANACONDA_TOKEN
      --python=3.5 recipe/meta.yaml
  except:
    - tags
